require "__AncientKnowledge__.prototypes.nexus-lab"
require "__AncientKnowledge__.prototypes.pylon"
require "__AncientKnowledge__.prototypes.refresher"
-- require "__AncientKnowledge__.prototypes.ancient-forge"
require "__AncientKnowledge__.prototypes.intermediate-items"
require "__AncientKnowledge__.prototypes.recipes"
require "__AncientKnowledge__.prototypes.finished-items"
require "__AncientKnowledge__.prototypes.projectiles"
require "__AncientKnowledge__.prototypes.living-accumulator"
require "__AncientKnowledge__.prototypes.fulgora-solar-panel"
-- require "__AncientKnowledge__.prototypes.mineables"
-- require "__AncientKnowledge__.prototypes.base-items"
-- require "__AncientKnowledge__.prototypes.equipment"
require "__AncientKnowledge__.prototypes.techonlogies"
require "__AncientKnowledge__.prototypes.recipe-technologies"
require "__AncientKnowledge__.prototypes.friendly-biter"
